In [1]:
import pandas as pd
data_cups = pd.read_csv('WorldCups.csv')
data_cups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [2]:
data_cups.set_index('Year')

,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
Year,,,,,,,,,
1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [3]:
data_cups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [4]:
data_cups.set_index('Year')['Winner']

Year
1930       Uruguay
1934         Italy
1938         Italy
1950       Uruguay
1954    Germany FR
1958        Brazil
1962        Brazil
1966       England
1970        Brazil
1974    Germany FR
1978     Argentina
1982         Italy
1986     Argentina
1990    Germany FR
1994        Brazil
1998        France
2002        Brazil
2006         Italy
2010         Spain
2014       Germany
Name: Winner, dtype: object

In [5]:
data_cups['Winner']=data_cups['Winner'].str.replace('Germany FR','Germany')

In [6]:
data_cups['Winner']

0       Uruguay
1         Italy
2         Italy
3       Uruguay
4       Germany
5        Brazil
6        Brazil
7       England
8        Brazil
9       Germany
10    Argentina
11        Italy
12    Argentina
13      Germany
14       Brazil
15       France
16       Brazil
17        Italy
18        Spain
19      Germany
Name: Winner, dtype: object

In [7]:
data_cups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [8]:
data_cups['Winner'].str.lower()

0       uruguay
1         italy
2         italy
3       uruguay
4       germany
5        brazil
6        brazil
7       england
8        brazil
9       germany
10    argentina
11        italy
12    argentina
13      germany
14       brazil
15       france
16       brazil
17        italy
18        spain
19      germany
Name: Winner, dtype: object

In [11]:
data_cups["Winner"].value_counts().index[0]

'Brazil'

In [12]:
data_cups["Winner"].value_counts()

Brazil       5
Italy        4
Germany      4
Argentina    2
Uruguay      2
England      1
Spain        1
France       1
Name: Winner, dtype: int64

In [21]:
data_cups['GoalsScored'].sort_values()

0      70
1      70
2      84
3      88
7      89
6      89
8      95
9      97
10    102
13    115
5     126
12    132
4     140
14    141
18    145
11    146
17    147
16    161
15    171
19    171
Name: GoalsScored, dtype: int64

In [22]:
data_cups['GoalsScored'].sort_values(ascending=False)

19    171
15    171
16    161
17    147
11    146
18    145
14    141
4     140
12    132
5     126
13    115
10    102
9      97
8      95
6      89
7      89
3      88
2      84
1      70
0      70
Name: GoalsScored, dtype: int64

In [23]:
data_cups.sort_values(by=['GoalsScored'])

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
13,1990,Italy,Germany,Argentina,Italy,England,115,24,52,2.516.215
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
4,1954,Switzerland,Germany,Hungary,Austria,Uruguay,140,16,26,768.607
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810